### PR TITLE
Add ClipboardManager system service binding

### PR DESCRIPTION
**Pull request by chenthorne**

### CODE REVIEW

**Comment by stephanenicolas** [comment]
Oh ! Cody ;)

Howdy dude ?

Thx for the PR, we will try to release it ASAP just for you ;)

2018-05-25 11:36 GMT-07:00 Coveralls <notifications@github.com>:

**Comment by chenthorne** [comment]
Hey! We're using TP at my new gig, so far working great. No rush on the release, we have a workaround in place that's not bad, just adding for completeness!

**Comment by stephanenicolas** [comment]
@chenthorne Hi Cody, FYI your PR is gonna be part of TP 2 that's gonna be release soon. We saw you closed all PRs, did you stop using TP ? (you can reach on Hang Out.. ;))

**Comment by stephanenicolas** [comment]
I close the PR as we're doing some clean up. This will be part of TP2.

**Pull request closed without merging**
